### ISSUE TITLE
GP RealEstate repository

### ISSUE THREAD

**Issue by NullCase** [SuperPyroManiac/GriefNotice#1]
Hi, I wish to maintain GP Real Estate.

Would you please put your repository online? I would like to fork it to continue working on it.

Its OK I understand you're busy. If you wish, I can pay you to put GP Real Estate back online to compensate you for your time.

Thanks in advance, and apologies for contacting you this way. I did not know how else to.

**Comment by SuperPyroManiac** [comment]
I got a couple messages with foul language, and they insulted me personally for no longer wanting to add rent. I have not played Minecraft in over a year, as I currently work for the Police. I don't have time to be insulted for a project of my own that I kept up free. That's the reason I removed it. I no longer have the source code or any of it. Sorry but I can't. You can probably find older versions somewhere else. You do have my permission to update it if you find an old copy.

**Comment by NullCase** [comment]
Thanks, I will. Very sad to hear about your current job. I hope you quickly find your way to private security. Then you'll work for people who freely choose to pay for your services. You'll never know that working for the police. Good luck.
